package com.myspace.puntosencillo;

/**
 * This class was automatically generated by the data modeler tool.
 */

/**
 * <p>
 * Java class for detailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="detailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bezeichnung" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="plz" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class DetailsType implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("bezeichnung")
	private java.lang.String bezeichnung;
	@org.kie.api.definition.type.Label("bic")
	private java.lang.String bic;
	@org.kie.api.definition.type.Label("ort")
	private java.lang.String ort;
	@org.kie.api.definition.type.Label("plz")
	private java.lang.String plz;

	public DetailsType() {
	}

	public java.lang.String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(java.lang.String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	public java.lang.String getBic() {
		return this.bic;
	}

	public void setBic(java.lang.String bic) {
		this.bic = bic;
	}

	public java.lang.String getOrt() {
		return this.ort;
	}

	public void setOrt(java.lang.String ort) {
		this.ort = ort;
	}

	public java.lang.String getPlz() {
		return this.plz;
	}

	public void setPlz(java.lang.String plz) {
		this.plz = plz;
	}

	public DetailsType(java.lang.String bezeichnung, java.lang.String bic,
			java.lang.String ort, java.lang.String plz) {
		this.bezeichnung = bezeichnung;
		this.bic = bic;
		this.ort = ort;
		this.plz = plz;
	}

}